### ISSUE TITLE
Unnecessary class value when composing empty classes

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [GeorgeTaveras1231/a-css-loader#11]
When composing classes while leaving the composite class empty, the css-modules parsers create an unnecessary value that adds unnecessary weight to the code. 

```css
.a1 {
  composes: a2 b2 from 'another-module'
}
```

```js
import styles from 'my-module'

console.log(styles.a1) // logs "a1 a2 b2"...."a1" is unnecessary since it applies no styles
```
